### ISSUE TITLE
Default dataset generates level 6 membership for all sample_IDs

### ISSUE THREAD

**Issue by CZell009** [leppott/BCGcalc#45]
When using the default dataset "Data_BCG_PacNW.xlsx", level assignment all sample n= 678 IDs is 6. This was conducted in R 3.5.2. with the latest version of the BCGCalc. I have reproduced this result multiple times. I would expect level assignment to range from 2 - 6 for these samples representing the calibration dataset.

Here is a screenshot of the output...
![image](https://user-images.githubusercontent.com/47162823/51949162-5b204a00-23e0-11e9-9adc-4014186598fa.png)

**Comment by leppott** [comment]
Percent metrics still 0-1 (instead of 0-100) for rules and checks.
